dist: trusty
sudo: required
language: node_js

cache:
  directories:
    - node_modules
  
install:
  - npm install --silent

jobs:
  include:
    - stage: test
      script: npm run test

notifications:
  email:
    on_success: never
    on_failure: never
    